import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const hussar = localFont({
  src: "./fonts/HussarVF.woff",
  variable: "--font-hussar",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hussar.variable} ${geistSans.variable} ${geistMono.variable} antialiased flex items-start font-sans justify-between`}
      >
        <Sidebar />
        <Toaster />
        <main className="w-full h-full pl-[180px]">{children}</main>
      </body>
    </html>
  );
}
